"""empty message

Revision ID: 1e49c7f3be30
Revises: 9a27f7dde213
Create Date: 2026-04-23 11:26:14.354091

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1e49c7f3be30'
down_revision = '9a27f7dde213'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('organizations', schema=None) as batch_op:
        batch_op.add_column(sa.Column('suspension_reason', sa.String(length=255), nullable=True))
        batch_op.create_foreign_key('fk_organization_owner', 'users', ['owner_id'], ['id'], use_alter=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('organizations', schema=None) as batch_op:
        batch_op.drop_constraint('fk_organization_owner', type_='foreignkey')
        batch_op.drop_column('suspension_reason')

    # ### end Alembic commands ###
