"""empty message

Revision ID: 26fb87e16db2
Revises: cbcb7a495b5c
Create Date: 2026-04-25 00:52:53.995491

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '26fb87e16db2'
down_revision = 'cbcb7a495b5c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('clinics', schema=None) as batch_op:
        batch_op.add_column(sa.Column('telefono', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('correo', sa.String(length=120), nullable=True))
        batch_op.add_column(sa.Column('suspension_reason', sa.String(length=255), nullable=True))

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_active', sa.Boolean(), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('is_active')

    with op.batch_alter_table('clinics', schema=None) as batch_op:
        batch_op.drop_column('suspension_reason')
        batch_op.drop_column('correo')
        batch_op.drop_column('telefono')

    # ### end Alembic commands ###
